### ISSUE TITLE
Horizontal align per table column

### ISSUE THREAD

**Issue by PanderMusubi** [helloflask/bootstrap-flask#95]
Please support horizontal align for rendering of `td` in tables, similar to how table header titles are overridden.

Default is align left, as is now. User should be able to override that explicitely with align left, center and  right. Only the `td` of a column are affected, not the `th`.

For example `render_table(colum_align=[('id', 'right'), ('status', 'center')])` which will keep the other columns aligned left.

Optionally, also support overiding vertical align per column, e.g. `colum_align=[..., ('status', 'center,vtop/vcenter/vbottom')]` or something more approprite.

**Comment by Yuxiaoy1** [comment]
I think there is no such need in most cases, but it apparently would increase the complexity of the code.
I recommend you can achieve that with some css:
```css
<style>
...
tr td:nth-child(2) {
    text-align:center;
    vertical-align:middle;
}
...
</style>
```
